package pmi.pssynchro;

import java.awt.Color;

//import java.io.IOException;
//import javax.swing.SwingUtilities;
/**
 *
 * @author nicola
 */
public class Configurazione extends javax.swing.JFrame {

    MainForm main = new MainForm();

    /**
     * Creates new form Configurazione
     */
    public Configurazione() {
        initComponents();
        this.getContentPane().setBackground(Color.getHSBColor(Costanti.HUE, Costanti.SATURATION, Costanti.BRIGHTNESS));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salva = new javax.swing.JButton();
        Chiudi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jIFConfGenerale = new javax.swing.JInternalFrame();
        jTextFieldStat = new javax.swing.JTextField();
        jTextFieldGiac = new javax.swing.JTextField();
        jTextFieldUrl = new javax.swing.JTextField();
        jLabelImm = new javax.swing.JLabel();
        jLabelCli = new javax.swing.JLabel();
        jTextFieldCli = new javax.swing.JTextField();
        jTextFieldOrd = new javax.swing.JTextField();
        jLabelMar = new javax.swing.JLabel();
        jTextFieldSca = new javax.swing.JTextField();
        jLabelCatPs = new javax.swing.JLabel();
        jLabelOrd = new javax.swing.JLabel();
        jLabelUrl = new javax.swing.JLabel();
        jTextFieldCodRif = new javax.swing.JTextField();
        jLabelLin1 = new javax.swing.JLabel();
        jLabelArt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldAll = new javax.swing.JTextField();
        jTextFieldMar = new javax.swing.JTextField();
        jTextFieldClean = new javax.swing.JTextField();
        jTextFieldArt = new javax.swing.JTextField();
        jLabelFor = new javax.swing.JLabel();
        jLabelSca = new javax.swing.JLabel();
        jTextFieldImm = new javax.swing.JTextField();
        jTextFieldFor = new javax.swing.JTextField();
        jLabelLin = new javax.swing.JLabel();
        jLabelAll = new javax.swing.JLabel();
        jTextFieldLis = new javax.swing.JTextField();
        jTextFieldLin = new javax.swing.JTextField();
        chkCatPs = new javax.swing.JCheckBox();
        jLabelGiac = new javax.swing.JLabel();
        jLabelSta = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jIFFtpImmagini = new javax.swing.JInternalFrame();
        jTextFieldPwdFtp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldCartellaFtp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldUrlCheckImg = new javax.swing.JTextField();
        jTextFieldNomeImgFtp = new javax.swing.JTextField();
        jTextFieldUsernameFtp = new javax.swing.JTextField();
        jTextFieldFtp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPercorsoImgFtp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jIFDatiSql = new javax.swing.JInternalFrame();
        jTextFieldSer = new javax.swing.JTextField();
        jTextFieldDb = new javax.swing.JTextField();
        jLabelServer = new javax.swing.JLabel();
        jLabelPwd = new javax.swing.JLabel();
        jTextFieldPwd = new javax.swing.JTextField();
        jLabelUser = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jLabelDb = new javax.swing.JLabel();
        jIFMagazzinoEsterno = new javax.swing.JInternalFrame();
        jTextFieldUrlMag = new javax.swing.JTextField();
        jLabelUrlMag = new javax.swing.JLabel();
        jTextFieldCodMag = new javax.swing.JTextField();
        jTextFieldMag = new javax.swing.JTextField();
        jLabelMag = new javax.swing.JLabel();
        jLabelFreqMag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurazione");
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salva.setBackground(java.awt.Color.lightGray);
        Salva.setText("Salva");
        Salva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvaActionPerformed(evt);
            }
        });
        getContentPane().add(Salva, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 418, -1, -1));

        Chiudi.setBackground(java.awt.Color.lightGray);
        Chiudi.setText("Chiudi");
        Chiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChiudiActionPerformed(evt);
            }
        });
        getContentPane().add(Chiudi, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 418, -1, -1));

        jLabel3.setMaximumSize(new java.awt.Dimension(128, 128));
        jLabel3.setMinimumSize(new java.awt.Dimension(128, 128));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 418, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info.png"))); // NOI18N
        jLabel4.setToolTipText("<html>\n<b>Conversione in minuti:</b><br>\n1 ora = <b>60</b><br>\n1 giorno = <b>1440</b><br>\n1 settimana = <b>10080</b><br>\n1 mese = <b>43800</b><br>\n");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 418, -1, -1));
        jLabel4.getAccessibleContext().setAccessibleDescription("info");

        jIFConfGenerale.setTitle("Configurazione generale");
        jIFConfGenerale.setAutoscrolls(true);
        jIFConfGenerale.setVisible(true);

        jTextFieldStat.setText(Config.getString("STATISTICHE")
        );
        jTextFieldStat.setToolTipText("Frequenza aggiornamento in minuti");

        jTextFieldGiac.setText(Config.getString("GIACENZA"));
        jTextFieldGiac.setToolTipText("Frequenza aggiornamento in minuti");

        jTextFieldUrl.setText(Config.getString("URL")
        );
        jTextFieldUrl.setName(""); // NOI18N

        jLabelImm.setText("Immagini");

        jLabelCli.setText("Clienti");

        jTextFieldCli.setText(Config.getString("CLIENTI"));
        jTextFieldCli.setToolTipText("Frequenza aggiornamento in minuti");

        jTextFieldOrd.setText(Config.getString("ORDINI")
        );
        jTextFieldOrd.setToolTipText("Frequenza aggiornamento in minuti");
        jTextFieldOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOrdActionPerformed(evt);
            }
        });

        jLabelMar.setText("Marche");

        jTextFieldSca.setText(Config.getString("SCADENZARIO"));
        jTextFieldSca.setToolTipText("Frequenza aggiornamento in minuti");

        jLabelCatPs.setText("Categorie PS");

        jLabelOrd.setText("Ordini");

        jLabelUrl.setText("Url: ");
        jLabelUrl.setToolTipText("");

        jTextFieldCodRif.setText(Config.getString("CODICI_RIFERIMENTO"));
        jTextFieldCodRif.setToolTipText("Frequenza aggiornamento in minuti");
        jTextFieldCodRif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodRifActionPerformed(evt);
            }
        });

        jLabelLin1.setText("Pulizia Area");

        jLabelArt.setText("Articoli");

        jLabel6.setText("Cod. Rif.");

        jTextFieldAll.setText(Config.getString("ALLEGATI"));
        jTextFieldAll.setToolTipText("Frequenza aggiornamento in minuti");
        jTextFieldAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAllActionPerformed(evt);
            }
        });

        jTextFieldMar.setText(Config.getString("MARCHE"));
        jTextFieldMar.setToolTipText("Frequenza aggiornamento in minuti");

        jTextFieldClean.setText(Config.getString("PULIZIAAREA")
        );
        jTextFieldClean.setToolTipText("Inserire ogni quanti minuti va ripulita l'area di visualizzazione dei dati");
        jTextFieldClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCleanActionPerformed(evt);
            }
        });

        jTextFieldArt.setText(Config.getString("ARTICOLI"));
        jTextFieldArt.setToolTipText("Frequenza aggiornamento in minuti");

        jLabelFor.setText("Fornitori");

        jLabelSca.setText("Scadenzario");

        jTextFieldImm.setText(Config.getString("IMMAGINI"));
        jTextFieldImm.setToolTipText("Frequenza aggiornamento in minuti");
        jTextFieldImm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldImmActionPerformed(evt);
            }
        });

        jTextFieldFor.setText(Config.getString("FORNITORI"));
        jTextFieldFor.setToolTipText("Frequenza aggiornamento in minuti");

        jLabelLin.setText("Lingue");

        jLabelAll.setText("Allegati");

        jTextFieldLis.setText(Config.getString("LISTINI"));
        jTextFieldLis.setToolTipText("Frequenza aggiornamento in minuti");
        jTextFieldLis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLisActionPerformed(evt);
            }
        });

        jTextFieldLin.setText(Config.getString("LINGUE")
        );
        jTextFieldLin.setToolTipText("Frequenza aggiornamento in minuti");
        jTextFieldLin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLinActionPerformed(evt);
            }
        });

        chkCatPs.setBackground(Color.getHSBColor(Costanti.HUE,Costanti.SATURATION,Costanti.BRIGHTNESS));
        if (Config.getString("CATEGORIEPS").equals("1"))
        chkCatPs.setSelected(true);
        else
        chkCatPs.setSelected(false);
        chkCatPs.setToolTipText("");
        chkCatPs.setFocusable(false);
        chkCatPs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chkCatPs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelGiac.setText("Giacenze");

        jLabelSta.setText("Statistiche");

        jLabel5.setText("Listini");

        javax.swing.GroupLayout jIFConfGeneraleLayout = new javax.swing.GroupLayout(jIFConfGenerale.getContentPane());
        jIFConfGenerale.getContentPane().setLayout(jIFConfGeneraleLayout);
        jIFConfGeneraleLayout.setHorizontalGroup(
            jIFConfGeneraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIFConfGeneraleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jIFConfGeneraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUrl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGiac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jIFConfGeneraleLayout.createSequentialGroup()
                        .addGroup(jIFConfGeneraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelImm)
                            .addComponent(jLabelFor)
                            .addComponent(jLabel5)
                            .addComponent(jLabelCatPs)
                            .addComponent(jLabelArt)
                            .addComponent(jLabelMar))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jIFConfGeneraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldUrl)
                    .addComponent(chkCatPs)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jIFConfGeneraleLayout.createSequentialGroup()
                        .addGroup(jIFConfGeneraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldGiac, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCli, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldArt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLis, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldImm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(jIFConfGeneraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAll)
                            .addComponent(jLabelSca)
                            .addComponent(jLabelSta)
                            .addComponent(jLabelOrd)
                            .addComponent(jLabelLin)
                            .addComponent(jLabelLin1)
                            .addComponent(jLabel6))
                        .addGap(37, 37, 37)
                        .addGroup(jIFConfGeneraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldClean, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAll, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldStat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCodRif, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59))
        );
        jIFConfGeneraleLayout.setVerticalGroup(
            jIFConfGeneraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIFConfGeneraleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jIFConfGeneraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jIFConfGeneraleLayout.createSequentialGroup()
                        .addComponent(jTextFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jIFConfGeneraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jIFConfGeneraleLayout.createSequentialGroup()
                                .addComponent(jTextFieldGiac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldImm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldLis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jIFConfGeneraleLayout.createSequentialGroup()
                                .addGroup(jIFConfGeneraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelAll))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jIFConfGeneraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldSca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSca))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jIFConfGeneraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jIFConfGeneraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldOrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelOrd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jIFConfGeneraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldLin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelLin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jIFConfGeneraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldClean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelLin1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jIFConfGeneraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextFieldCodRif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkCatPs))
                    .addGroup(jIFConfGeneraleLayout.createSequentialGroup()
                        .addComponent(jLabelUrl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGiac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelArt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelImm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCatPs)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Configurazione generale", jIFConfGenerale);

        jIFFtpImmagini.setTitle("Ftp  Immagini");
        jIFFtpImmagini.setMinimumSize(new java.awt.Dimension(520, 201));
        jIFFtpImmagini.setVisible(true);

        jTextFieldPwdFtp.setText(Config.getString("PASSWORD_FTP"));
        jTextFieldPwdFtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPwdFtpActionPerformed(evt);
            }
        });

        jLabel7.setText("Indirizzo");

        jLabel13.setText("Url Check Immagini");

        jTextFieldCartellaFtp.setText(Config.getString("SCAMBIO_FTP")
        );
        jTextFieldCartellaFtp.setName(""); // NOI18N
        jTextFieldCartellaFtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCartellaFtpActionPerformed(evt);
            }
        });

        jLabel12.setText("Nome File");

        jLabel10.setText("Cartella remota");

        jTextFieldUrlCheckImg.setText(Config.getString("URL_CHECK_IMMAGINI")
        );
        jTextFieldUrlCheckImg.setName(""); // NOI18N
        jTextFieldUrlCheckImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUrlCheckImgActionPerformed(evt);
            }
        });

        jTextFieldNomeImgFtp.setText(Config.getString("IMMAGINE_FTP")
        );
        jTextFieldNomeImgFtp.setName(""); // NOI18N
        jTextFieldNomeImgFtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeImgFtpActionPerformed(evt);
            }
        });

        jTextFieldUsernameFtp.setText(Config.getString("USERNAME_FTP"));

        jTextFieldFtp.setText(Config.getString("FTP")
        );
        jTextFieldFtp.setName(""); // NOI18N
        jTextFieldFtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFtpActionPerformed(evt);
            }
        });

        jLabel8.setText("Username");

        jTextFieldPercorsoImgFtp.setText(Config.getString("PERCORSO_IMMAGINE_FTP")
        );
        jTextFieldPercorsoImgFtp.setName(""); // NOI18N
        jTextFieldPercorsoImgFtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPercorsoImgFtpActionPerformed(evt);
            }
        });

        jLabel9.setText("Password");

        jLabel11.setText("Percorso Immagini");

        javax.swing.GroupLayout jIFFtpImmaginiLayout = new javax.swing.GroupLayout(jIFFtpImmagini.getContentPane());
        jIFFtpImmagini.getContentPane().setLayout(jIFFtpImmaginiLayout);
        jIFFtpImmaginiLayout.setHorizontalGroup(
            jIFFtpImmaginiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIFFtpImmaginiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jIFFtpImmaginiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jIFFtpImmaginiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jIFFtpImmaginiLayout.createSequentialGroup()
                        .addComponent(jTextFieldUsernameFtp, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPwdFtp))
                    .addComponent(jTextFieldCartellaFtp)
                    .addComponent(jTextFieldUrlCheckImg)
                    .addComponent(jTextFieldPercorsoImgFtp)
                    .addComponent(jTextFieldNomeImgFtp)
                    .addComponent(jTextFieldFtp, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jIFFtpImmaginiLayout.setVerticalGroup(
            jIFFtpImmaginiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIFFtpImmaginiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jIFFtpImmaginiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldFtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jIFFtpImmaginiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldUsernameFtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPwdFtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jIFFtpImmaginiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCartellaFtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(7, 7, 7)
                .addGroup(jIFFtpImmaginiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUrlCheckImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jIFFtpImmaginiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPercorsoImgFtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jIFFtpImmaginiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeImgFtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ftp Immagini", jIFFtpImmagini);

        jIFDatiSql.setTitle("Dati Acceso SQL");
        jIFDatiSql.setAutoscrolls(true);
        jIFDatiSql.setVisible(true);

        jTextFieldSer.setText(Config.getString("SERVER"));
        jTextFieldSer.setToolTipText("es: nomeserver\\nomeistanzasql");

        jTextFieldDb.setText(Config.getString("DATABASE"));
        jTextFieldDb.setToolTipText("es: adb_demo");

        jLabelServer.setText("Server");

        jLabelPwd.setText("Password");

        jTextFieldPwd.setText(Config.getString("PASSWORD"));
        jTextFieldPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPwdActionPerformed(evt);
            }
        });

        jLabelUser.setText("Username");

        jTextFieldUser.setText(Config.getString("USERNAME"));

        jLabelDb.setText("Database");

        javax.swing.GroupLayout jIFDatiSqlLayout = new javax.swing.GroupLayout(jIFDatiSql.getContentPane());
        jIFDatiSql.getContentPane().setLayout(jIFDatiSqlLayout);
        jIFDatiSqlLayout.setHorizontalGroup(
            jIFDatiSqlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIFDatiSqlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jIFDatiSqlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDb)
                    .addComponent(jLabelServer)
                    .addComponent(jLabelUser))
                .addGap(53, 53, 53)
                .addGroup(jIFDatiSqlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jIFDatiSqlLayout.createSequentialGroup()
                        .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPwd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldSer)
                    .addComponent(jTextFieldDb))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jIFDatiSqlLayout.setVerticalGroup(
            jIFDatiSqlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIFDatiSqlLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jIFDatiSqlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDb)
                    .addComponent(jTextFieldDb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jIFDatiSqlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jIFDatiSqlLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelServer))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jIFDatiSqlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jIFDatiSqlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUser)
                    .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPwd)
                    .addComponent(jTextFieldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(268, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dati SQL", jIFDatiSql);

        jIFMagazzinoEsterno.setTitle("Magazzino Esterno");
        jIFMagazzinoEsterno.setAutoscrolls(true);
        jIFMagazzinoEsterno.setVisible(true);

        jTextFieldUrlMag.setText(Config.getString("URLMAGAZZINO")
        );
        jTextFieldUrlMag.setToolTipText("Indirizzo da cui prelevare il csv con le giacenze");
        jTextFieldUrlMag.setName(""); // NOI18N
        jTextFieldUrlMag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUrlMagActionPerformed(evt);
            }
        });

        jLabelUrlMag.setText("Url: ");
        jLabelUrlMag.setToolTipText("");

        jTextFieldCodMag.setText(Config.getString("CODICEMAGAZZINO"));
        jTextFieldCodMag.setToolTipText("Codice del magazzino in Arca");
        jTextFieldCodMag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodMagActionPerformed(evt);
            }
        });

        jTextFieldMag.setText(Config.getString("MAGAZZINO")
        );
        jTextFieldMag.setToolTipText("Frequenza aggiornamento in minuti");
        jTextFieldMag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMagActionPerformed(evt);
            }
        });

        jLabelMag.setText("Cod. Mag.");

        jLabelFreqMag.setText("Frequenza");

        javax.swing.GroupLayout jIFMagazzinoEsternoLayout = new javax.swing.GroupLayout(jIFMagazzinoEsterno.getContentPane());
        jIFMagazzinoEsterno.getContentPane().setLayout(jIFMagazzinoEsternoLayout);
        jIFMagazzinoEsternoLayout.setHorizontalGroup(
            jIFMagazzinoEsternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIFMagazzinoEsternoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jIFMagazzinoEsternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMag)
                    .addComponent(jLabelUrlMag, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jIFMagazzinoEsternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldUrlMag, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jIFMagazzinoEsternoLayout.createSequentialGroup()
                        .addComponent(jTextFieldCodMag, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addGroup(jIFMagazzinoEsternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFreqMag)
                            .addGroup(jIFMagazzinoEsternoLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jTextFieldMag, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jIFMagazzinoEsternoLayout.setVerticalGroup(
            jIFMagazzinoEsternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIFMagazzinoEsternoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jIFMagazzinoEsternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUrlMag)
                    .addComponent(jTextFieldUrlMag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jIFMagazzinoEsternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFreqMag)
                    .addComponent(jTextFieldCodMag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMag))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mag. Esterno", jIFMagazzinoEsterno);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jTextFieldAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAllActionPerformed

    private void SalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvaActionPerformed
        Config.setProperty("URL", jTextFieldUrl.getText());
        Config.setProperty("GIACENZA", jTextFieldGiac.getText());
        Config.setProperty("CLIENTI", jTextFieldCli.getText());
        Config.setProperty("ARTICOLI", jTextFieldArt.getText());
        Config.setProperty("FORNITORI", jTextFieldFor.getText());
        Config.setProperty("IMMAGINI", jTextFieldImm.getText());
        Config.setProperty("ALLEGATI", jTextFieldAll.getText());
        Config.setProperty("SCADENZARIO", jTextFieldSca.getText());
        Config.setProperty("STATISTICHE", jTextFieldStat.getText());
        Config.setProperty("MARCHE", jTextFieldMar.getText());
        Config.setProperty("ORDINI", jTextFieldOrd.getText());
        Config.setProperty("LINGUE", jTextFieldLin.getText());
        Config.setProperty("DATABASE", jTextFieldDb.getText());
        Config.setProperty("SERVER", jTextFieldSer.getText());
        Config.setProperty("USERNAME", jTextFieldUser.getText());
        Config.setProperty("PASSWORD", jTextFieldPwd.getText());
        Config.setProperty("PULIZIAAREA", jTextFieldClean.getText());
        Config.setProperty("URLMAGAZZINO", jTextFieldUrlMag.getText());
        Config.setProperty("CODICEMAGAZZINO", jTextFieldCodMag.getText());
        Config.setProperty("MAGAZZINO", jTextFieldMag.getText());
        Config.setProperty("LISTINI", jTextFieldLis.getText());
        Config.setProperty("CODICI_RIFERIMENTO", jTextFieldCodRif.getText());
        Config.setProperty("FTP", jTextFieldFtp.getText());
        Config.setProperty("USERNAME_FTP", jTextFieldUsernameFtp.getText());
        Config.setProperty("PASSWORD_FTP", jTextFieldPwdFtp.getText());
        Config.setProperty("SCAMBIO_FTP", jTextFieldCartellaFtp.getText());
        Config.setProperty("URL_CHECK_IMMAGINI", jTextFieldUrlCheckImg.getText());
        Config.setProperty("PERCORSO_IMMAGINE_FTP", jTextFieldPercorsoImgFtp.getText());
        Config.setProperty("IMMAGINE_FTP", jTextFieldNomeImgFtp.getText());
        String catPs = new String();
        if (chkCatPs.isSelected()) {
            catPs = "1";
        } else {
            catPs = "0";
        }
        Config.setProperty("CATEGORIEPS", catPs);
    }//GEN-LAST:event_SalvaActionPerformed

    private void ChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChiudiActionPerformed
        this.dispose();
    }//GEN-LAST:event_ChiudiActionPerformed

    private void jTextFieldOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOrdActionPerformed

    private void jTextFieldPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPwdActionPerformed

    private void jTextFieldLinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLinActionPerformed

    private void jTextFieldCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCleanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCleanActionPerformed

    private void jTextFieldMagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMagActionPerformed

    private void jTextFieldUrlMagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUrlMagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUrlMagActionPerformed

    private void jTextFieldCodMagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodMagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodMagActionPerformed

    private void jTextFieldImmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldImmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldImmActionPerformed

    private void jTextFieldLisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLisActionPerformed

    private void jTextFieldCodRifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodRifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodRifActionPerformed

    private void jTextFieldFtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFtpActionPerformed

    private void jTextFieldPwdFtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPwdFtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPwdFtpActionPerformed

    private void jTextFieldCartellaFtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCartellaFtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCartellaFtpActionPerformed

    private void jTextFieldPercorsoImgFtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPercorsoImgFtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPercorsoImgFtpActionPerformed

    private void jTextFieldNomeImgFtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeImgFtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeImgFtpActionPerformed

    private void jTextFieldUrlCheckImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUrlCheckImgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUrlCheckImgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configurazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configurazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configurazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configurazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configurazione().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Chiudi;
    private javax.swing.JButton Salva;
    private javax.swing.JCheckBox chkCatPs;
    private javax.swing.JInternalFrame jIFConfGenerale;
    private javax.swing.JInternalFrame jIFDatiSql;
    private javax.swing.JInternalFrame jIFFtpImmagini;
    private javax.swing.JInternalFrame jIFMagazzinoEsterno;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAll;
    private javax.swing.JLabel jLabelArt;
    private javax.swing.JLabel jLabelCatPs;
    private javax.swing.JLabel jLabelCli;
    private javax.swing.JLabel jLabelDb;
    private javax.swing.JLabel jLabelFor;
    private javax.swing.JLabel jLabelFreqMag;
    private javax.swing.JLabel jLabelGiac;
    private javax.swing.JLabel jLabelImm;
    private javax.swing.JLabel jLabelLin;
    private javax.swing.JLabel jLabelLin1;
    private javax.swing.JLabel jLabelMag;
    private javax.swing.JLabel jLabelMar;
    private javax.swing.JLabel jLabelOrd;
    private javax.swing.JLabel jLabelPwd;
    private javax.swing.JLabel jLabelSca;
    private javax.swing.JLabel jLabelServer;
    private javax.swing.JLabel jLabelSta;
    private javax.swing.JLabel jLabelUrl;
    private javax.swing.JLabel jLabelUrlMag;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldAll;
    private javax.swing.JTextField jTextFieldArt;
    private javax.swing.JTextField jTextFieldCartellaFtp;
    private javax.swing.JTextField jTextFieldClean;
    private javax.swing.JTextField jTextFieldCli;
    private javax.swing.JTextField jTextFieldCodMag;
    private javax.swing.JTextField jTextFieldCodRif;
    private javax.swing.JTextField jTextFieldDb;
    private javax.swing.JTextField jTextFieldFor;
    private javax.swing.JTextField jTextFieldFtp;
    private javax.swing.JTextField jTextFieldGiac;
    private javax.swing.JTextField jTextFieldImm;
    private javax.swing.JTextField jTextFieldLin;
    private javax.swing.JTextField jTextFieldLis;
    private javax.swing.JTextField jTextFieldMag;
    private javax.swing.JTextField jTextFieldMar;
    private javax.swing.JTextField jTextFieldNomeImgFtp;
    private javax.swing.JTextField jTextFieldOrd;
    private javax.swing.JTextField jTextFieldPercorsoImgFtp;
    private javax.swing.JTextField jTextFieldPwd;
    private javax.swing.JTextField jTextFieldPwdFtp;
    private javax.swing.JTextField jTextFieldSca;
    private javax.swing.JTextField jTextFieldSer;
    private javax.swing.JTextField jTextFieldStat;
    private javax.swing.JTextField jTextFieldUrl;
    private javax.swing.JTextField jTextFieldUrlCheckImg;
    private javax.swing.JTextField jTextFieldUrlMag;
    private javax.swing.JTextField jTextFieldUser;
    private javax.swing.JTextField jTextFieldUsernameFtp;
    // End of variables declaration//GEN-END:variables
}
