package pmi.pssynchro;


//import java.io.IOException;
//import javax.swing.SwingUtilities;

/**
 *
 * @author nicola
 */
public class Configurazione extends javax.swing.JFrame {

    /**
     * Creates new form Configurazione
     */
    public Configurazione() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldUrl = new javax.swing.JTextField();
        jLabelUrl = new javax.swing.JLabel();
        jLabelGiac = new javax.swing.JLabel();
        jTextFieldGiac = new javax.swing.JTextField();
        jLabelCli = new javax.swing.JLabel();
        jTextFieldCli = new javax.swing.JTextField();
        jLabelFor = new javax.swing.JLabel();
        jTextFieldFor = new javax.swing.JTextField();
        jLabelArt = new javax.swing.JLabel();
        jTextFieldArt = new javax.swing.JTextField();
        jLabelMar = new javax.swing.JLabel();
        jTextFieldMar = new javax.swing.JTextField();
        jLabelImm = new javax.swing.JLabel();
        jTextFieldAll = new javax.swing.JTextField();
        jLabelAll = new javax.swing.JLabel();
        jTextFieldImm = new javax.swing.JTextField();
        jLabelSca = new javax.swing.JLabel();
        jTextFieldSca = new javax.swing.JTextField();
        jLabelSta = new javax.swing.JLabel();
        jTextFieldStat = new javax.swing.JTextField();
        jLabelOrd = new javax.swing.JLabel();
        jTextFieldOrd = new javax.swing.JTextField();
        jLabelLin = new javax.swing.JLabel();
        jTextFieldLin = new javax.swing.JTextField();
        Salva = new javax.swing.JButton();
        Chiudi = new javax.swing.JButton();
        jLabelDb = new javax.swing.JLabel();
        jLabelServer = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelPwd = new javax.swing.JLabel();
        jTextFieldDb = new javax.swing.JTextField();
        jTextFieldSer = new javax.swing.JTextField();
        jTextFieldUser = new javax.swing.JTextField();
        jTextFieldPwd = new javax.swing.JTextField();
        jTextFieldClean = new javax.swing.JTextField();
        jLabelLin1 = new javax.swing.JLabel();
        jLabelMag = new javax.swing.JLabel();
        jTextFieldCodMag = new javax.swing.JTextField();
        jLabelFreqMag = new javax.swing.JLabel();
        jTextFieldMag = new javax.swing.JTextField();
        jTextFieldUrlMag = new javax.swing.JTextField();
        jLabelUrlMag = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldLis = new javax.swing.JTextField();
        jLabelCatPs = new javax.swing.JLabel();
        chkCatPs = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTextFieldUrl.setText(Config.getString("URL")
        );
        jTextFieldUrl.setName(""); // NOI18N

        jLabelUrl.setText("Url: ");
        jLabelUrl.setToolTipText("");

        jLabelGiac.setText("Giacenze");

        jTextFieldGiac.setText(Config.getString("GIACENZA"));
        jTextFieldGiac.setToolTipText("Frequenza aggiornamento in minuti");

        jLabelCli.setText("Clienti");

        jTextFieldCli.setText(Config.getString("CLIENTI"));
        jTextFieldCli.setToolTipText("Frequenza aggiornamento in minuti");

        jLabelFor.setText("Fornitori");

        jTextFieldFor.setText(Config.getString("FORNITORI"));
        jTextFieldFor.setToolTipText("Frequenza aggiornamento in minuti");

        jLabelArt.setText("Articoli");

        jTextFieldArt.setText(Config.getString("ARTICOLI"));
        jTextFieldArt.setToolTipText("Frequenza aggiornamento in minuti");

        jLabelMar.setText("Marche");

        jTextFieldMar.setText(Config.getString("MARCHE"));
        jTextFieldMar.setToolTipText("Frequenza aggiornamento in minuti");

        jLabelImm.setText("Immagini");

        jTextFieldAll.setText(Config.getString("ALLEGATI"));
        jTextFieldAll.setToolTipText("Frequenza aggiornamento in minuti");
        jTextFieldAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAllActionPerformed(evt);
            }
        });

        jLabelAll.setText("Allegati");

        jTextFieldImm.setText(Config.getString("IMMAGINI"));
        jTextFieldImm.setToolTipText("Frequenza aggiornamento in minuti");
        jTextFieldImm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldImmActionPerformed(evt);
            }
        });

        jLabelSca.setText("Scadenzario");

        jTextFieldSca.setText(Config.getString("SCADENZARIO"));
        jTextFieldSca.setToolTipText("Frequenza aggiornamento in minuti");

        jLabelSta.setText("Statistiche");

        jTextFieldStat.setText(Config.getString("STATISTICHE")
        );
        jTextFieldStat.setToolTipText("Frequenza aggiornamento in minuti");

        jLabelOrd.setText("Ordini");

        jTextFieldOrd.setText(Config.getString("ORDINI")
        );
        jTextFieldOrd.setToolTipText("Frequenza aggiornamento in minuti");
        jTextFieldOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOrdActionPerformed(evt);
            }
        });

        jLabelLin.setText("Lingue");

        jTextFieldLin.setText(Config.getString("LINGUE")
        );
        jTextFieldLin.setToolTipText("Frequenza aggiornamento in minuti");
        jTextFieldLin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLinActionPerformed(evt);
            }
        });

        Salva.setBackground(java.awt.Color.lightGray);
        Salva.setText("Salva");
        Salva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvaActionPerformed(evt);
            }
        });

        Chiudi.setBackground(java.awt.Color.lightGray);
        Chiudi.setText("Chiudi");
        Chiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChiudiActionPerformed(evt);
            }
        });

        jLabelDb.setText("Database");

        jLabelServer.setText("Server");

        jLabelUser.setText("Username");

        jLabelPwd.setText("Password");

        jTextFieldDb.setText(Config.getString("DATABASE"));
        jTextFieldDb.setToolTipText("es: adb_demo");

        jTextFieldSer.setText(Config.getString("SERVER"));
        jTextFieldSer.setToolTipText("es: nomeserver\\nomeistanzasql");

        jTextFieldUser.setText(Config.getString("USERNAME"));

        jTextFieldPwd.setText(Config.getString("PASSWORD"));
        jTextFieldPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPwdActionPerformed(evt);
            }
        });

        jTextFieldClean.setText(Config.getString("PULIZIAAREA")
        );
        jTextFieldClean.setToolTipText("Inserire ogni quanti minuti va ripulita l'area di visualizzazione dei dati");
        jTextFieldClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCleanActionPerformed(evt);
            }
        });

        jLabelLin1.setText("Pulizia Area");

        jLabelMag.setText("Cod. Mag.");

        jTextFieldCodMag.setText(Config.getString("CODICEMAGAZZINO"));
        jTextFieldCodMag.setToolTipText("Codice del magazzino in Arca");
        jTextFieldCodMag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodMagActionPerformed(evt);
            }
        });

        jLabelFreqMag.setText("Frequenza");

        jTextFieldMag.setText(Config.getString("MAGAZZINO")
        );
        jTextFieldMag.setToolTipText("Frequenza aggiornamento in minuti");
        jTextFieldMag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMagActionPerformed(evt);
            }
        });

        jTextFieldUrlMag.setText(Config.getString("URLMAGAZZINO")
        );
        jTextFieldUrlMag.setToolTipText("Indirizzo da cui prelevare il csv con le giacenze");
        jTextFieldUrlMag.setName(""); // NOI18N
        jTextFieldUrlMag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUrlMagActionPerformed(evt);
            }
        });

        jLabelUrlMag.setText("Url: ");
        jLabelUrlMag.setToolTipText("");

        jLabel1.setForeground(java.awt.Color.gray);
        jLabel1.setText("Magazzino esterno");

        jLabel2.setForeground(java.awt.Color.gray);
        jLabel2.setText("Dati accesso SQL");

        jLabel3.setMaximumSize(new java.awt.Dimension(128, 128));
        jLabel3.setMinimumSize(new java.awt.Dimension(128, 128));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info.png"))); // NOI18N
        jLabel4.setToolTipText("<html>\n<b>Conversione in minuti:</b><br>\n1 ora = <b>60</b><br>\n1 giorno = <b>1440</b><br>\n1 settimana = <b>10080</b><br>\n1 mese = <b>43800</b><br>\n");

        jLabel5.setText("Listini");

        jTextFieldLis.setText(Config.getString("LISTINI"));
        jTextFieldLis.setToolTipText("Frequenza aggiornamento in minuti");
        jTextFieldLis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLisActionPerformed(evt);
            }
        });

        jLabelCatPs.setText("Categorie PS");

        if (Config.getString("CATEGORIEPS").equals("1"))
        chkCatPs.setSelected(true);
        else
        chkCatPs.setSelected(false);
        chkCatPs.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelUrl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelGiac, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                        .addComponent(jLabelCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabelFor)
                                    .addComponent(jLabelArt)
                                    .addComponent(jLabelMar)
                                    .addComponent(jLabelImm)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldGiac, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCli, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldFor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldArt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldImm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldLis, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addGap(14, 14, 14)
                                        .addComponent(Salva)
                                        .addGap(18, 18, 18)
                                        .addComponent(Chiudi))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(215, 215, 215)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelAll)
                                            .addComponent(jLabelSca)
                                            .addComponent(jLabelSta)
                                            .addComponent(jLabelOrd)
                                            .addComponent(jLabelLin)
                                            .addComponent(jLabelLin1)
                                            .addComponent(jLabelCatPs))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldClean, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldAll, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldSca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldStat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldLin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chkCatPs))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelMag)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCodMag, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldUrlMag, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDb)
                            .addComponent(jLabelServer)
                            .addComponent(jLabelUser))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPwd)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldDb, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                .addComponent(jTextFieldSer)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(13, 13, 13)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelUrlMag, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(jLabelFreqMag))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(291, 291, 291)
                                .addComponent(jTextFieldMag, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUrl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldGiac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGiac))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCli)
                            .addComponent(jTextFieldCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelArt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAll))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldOrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOrd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLin))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelImm)
                        .addComponent(jTextFieldImm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldClean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelLin1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCatPs, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldLis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelCatPs)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUrlMag)
                    .addComponent(jTextFieldUrlMag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFreqMag)
                    .addComponent(jTextFieldCodMag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMag))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(19, 19, 19)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDb)
                            .addComponent(jTextFieldDb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelServer)
                            .addComponent(jTextFieldSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPwd)
                            .addComponent(jTextFieldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelUser))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Salva)
                        .addComponent(Chiudi)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(20, 20, 20))
        );

        jLabel4.getAccessibleContext().setAccessibleDescription("info");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    private void jTextFieldAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAllActionPerformed

    private void SalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvaActionPerformed
        Config.setProperty("URL", jTextFieldUrl.getText());
        Config.setProperty("GIACENZA", jTextFieldGiac.getText());
        Config.setProperty("CLIENTI", jTextFieldCli.getText());
        Config.setProperty("ARTICOLI", jTextFieldArt.getText());
        Config.setProperty("FORNITORI", jTextFieldFor.getText());
        Config.setProperty("IMMAGINI", jTextFieldImm.getText());
        Config.setProperty("ALLEGATI", jTextFieldAll.getText());
        Config.setProperty("SCADENZARIO", jTextFieldSca.getText());
        Config.setProperty("STATISTICHE", jTextFieldStat.getText());
        Config.setProperty("MARCHE", jTextFieldMar.getText());
        Config.setProperty("ORDINI", jTextFieldOrd.getText());
        Config.setProperty("LINGUE", jTextFieldLin.getText());
        Config.setProperty("DATABASE", jTextFieldDb.getText());
        Config.setProperty("SERVER", jTextFieldSer.getText());
        Config.setProperty("USERNAME", jTextFieldUser.getText());
        Config.setProperty("PASSWORD", jTextFieldPwd.getText());
        Config.setProperty("PULIZIAAREA", jTextFieldClean.getText());
        Config.setProperty("URLMAGAZZINO", jTextFieldUrlMag.getText());
        Config.setProperty("CODICEMAGAZZINO", jTextFieldCodMag.getText());
        Config.setProperty("MAGAZZINO", jTextFieldMag.getText());   
        Config.setProperty("LISTINI", jTextFieldLis.getText());
        String catPs = new String();
        if(chkCatPs.isSelected()) 
            catPs = "1";
        else
            catPs = "0";
        Config.setProperty("CATEGORIEPS", catPs);
    }//GEN-LAST:event_SalvaActionPerformed

    private void ChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChiudiActionPerformed
        this.dispose();
    }//GEN-LAST:event_ChiudiActionPerformed

    private void jTextFieldOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOrdActionPerformed

    private void jTextFieldPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPwdActionPerformed

    private void jTextFieldLinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLinActionPerformed

    private void jTextFieldCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCleanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCleanActionPerformed

    private void jTextFieldMagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMagActionPerformed

    private void jTextFieldUrlMagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUrlMagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUrlMagActionPerformed

    private void jTextFieldCodMagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodMagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodMagActionPerformed

    private void jTextFieldImmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldImmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldImmActionPerformed

    private void jTextFieldLisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configurazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configurazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configurazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configurazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configurazione().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Chiudi;
    private javax.swing.JButton Salva;
    private javax.swing.JCheckBox chkCatPs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAll;
    private javax.swing.JLabel jLabelArt;
    private javax.swing.JLabel jLabelCatPs;
    private javax.swing.JLabel jLabelCli;
    private javax.swing.JLabel jLabelDb;
    private javax.swing.JLabel jLabelFor;
    private javax.swing.JLabel jLabelFreqMag;
    private javax.swing.JLabel jLabelGiac;
    private javax.swing.JLabel jLabelImm;
    private javax.swing.JLabel jLabelLin;
    private javax.swing.JLabel jLabelLin1;
    private javax.swing.JLabel jLabelMag;
    private javax.swing.JLabel jLabelMar;
    private javax.swing.JLabel jLabelOrd;
    private javax.swing.JLabel jLabelPwd;
    private javax.swing.JLabel jLabelSca;
    private javax.swing.JLabel jLabelServer;
    private javax.swing.JLabel jLabelSta;
    private javax.swing.JLabel jLabelUrl;
    private javax.swing.JLabel jLabelUrlMag;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextFieldAll;
    private javax.swing.JTextField jTextFieldArt;
    private javax.swing.JTextField jTextFieldClean;
    private javax.swing.JTextField jTextFieldCli;
    private javax.swing.JTextField jTextFieldCodMag;
    private javax.swing.JTextField jTextFieldDb;
    private javax.swing.JTextField jTextFieldFor;
    private javax.swing.JTextField jTextFieldGiac;
    private javax.swing.JTextField jTextFieldImm;
    private javax.swing.JTextField jTextFieldLin;
    private javax.swing.JTextField jTextFieldLis;
    private javax.swing.JTextField jTextFieldMag;
    private javax.swing.JTextField jTextFieldMar;
    private javax.swing.JTextField jTextFieldOrd;
    private javax.swing.JTextField jTextFieldPwd;
    private javax.swing.JTextField jTextFieldSca;
    private javax.swing.JTextField jTextFieldSer;
    private javax.swing.JTextField jTextFieldStat;
    private javax.swing.JTextField jTextFieldUrl;
    private javax.swing.JTextField jTextFieldUrlMag;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
